name: Remover label da parent issue ao fechar issue pública

on:
  issues:
    types: [closed]

jobs:
  remove-label-from-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Buscar parent issue via API
        id: extract
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_PUBLIC_ROADMAP }}
          REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          set -e
          RESPONSE=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/relationships")
          echo "Resposta da API: $RESPONSE"
          # Ajuste o jq conforme o formato do JSON retornado pela API
          PARENT_ISSUE_NUMBER=$(echo "$RESPONSE" | jq -r '.parent.number // empty')
          if [ -z "$PARENT_ISSUE_NUMBER" ]; then
            echo "::error::Parent issue não encontrada via API."
            exit 1
          fi
          echo "parent_issue_number=$PARENT_ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Remover label da parent issue
        if: steps.extract.outputs.parent_issue_number != ''
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_PUBLIC_ROADMAP }}
          PARENT_URL_PROJECT_REPO: ${{ secrets.PARENT_URL_PROJECT_REPO }}
        run: |
          set -e
          PARENT_ISSUE_NUMBER="${{ steps.extract.outputs.parent_issue_number }}"
          PARENT_REPO="${PARENT_URL_PROJECT_REPO}"
          LABEL_TO_REMOVE="pronto-para-publicar"
          echo "Removendo label '$LABEL_TO_REMOVE' da issue $PARENT_ISSUE_NUMBER no repo $PARENT_REPO"
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}\n" -X DELETE \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$PARENT_REPO/issues/$PARENT_ISSUE_NUMBER/labels/$LABEL_TO_REMOVE")
          HTTP_STATUS=$(echo "$RESPONSE" | grep HTTP_STATUS | cut -d':' -f2)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS/d')
          echo "Status HTTP da requisição: $HTTP_STATUS"
          echo "Resposta da API:"
          echo "$BODY"
          if [ "$HTTP_STATUS" -ne 200 ] && [ "$HTTP_STATUS" -ne 204 ]; then
            echo "::error::Falha ao remover label. Status: $HTTP_STATUS"
            exit 1
          fi
