name: Remover label da parent issue ao fechar issue pública

on:
  issues:
    types: [closed]

jobs:
  remove-label-from-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Extrair parent issue do corpo
        id: extract
        run: |
          echo "Corpo da issue:"
          echo "${{ github.event.issue.body }}"
          BODY="${{ github.event.issue.body }}"
          # Extrai o número da parent issue do padrão "_Parent issue: [#123](...)_"
          PARENT_ISSUE_NUMBER=$(echo "$BODY" | grep -oP '_Parent issue: \[#\K[0-9]+')
          echo "Número extraído: $PARENT_ISSUE_NUMBER"
          if [ -z "$PARENT_ISSUE_NUMBER" ]; then
            echo "::error::Não foi possível extrair o número da parent issue."
            exit 1
          fi
          echo "parent_issue_number=$PARENT_ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Remover label da parent issue
        if: steps.extract.outputs.parent_issue_number != ''
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_PUBLIC_ROADMAP }}
          PARENT_URL_PROJECT_REPO: ${{ secrets.PARENT_URL_PROJECT_REPO }}
        run: |
          set -e
          PARENT_ISSUE_NUMBER="${{ steps.extract.outputs.parent_issue_number }}"
          PARENT_REPO="${PARENT_URL_PROJECT_REPO}"
          LABEL_TO_REMOVE="pronto-para-publicar"
          echo "Repositório alvo: $PARENT_REPO"
          echo "Issue alvo: $PARENT_ISSUE_NUMBER"
          echo "Label a remover: $LABEL_TO_REMOVE"
          curl -v -X DELETE \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$PARENT_REPO/issues/$PARENT_ISSUE_NUMBER/labels/$LABEL_TO_REMOVE"
